version: 2

project_name: light_vm

before:
  hooks:
    - go mod tidy
    - sh -c "cd web/frontend && npm ci && npm run build"

builds:
  - id: light_vm
    main: ./cmd/light_vm
    binary: light_vm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - light_vm.example.yml

dockers:
  - image_templates:
      - "ghcr.io/piyushkumar-1/light-vm:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/piyushKumar-1/light-vm"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    goarch: amd64
    dockerfile: Dockerfile.goreleaser

  - image_templates:
      - "ghcr.io/piyushkumar-1/light-vm:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source=https://github.com/piyushKumar-1/light-vm"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    goarch: arm64
    dockerfile: Dockerfile.goreleaser

docker_manifests:
  - name_template: "ghcr.io/piyushkumar-1/light-vm:{{ .Version }}"
    image_templates:
      - "ghcr.io/piyushkumar-1/light-vm:{{ .Version }}-amd64"
      - "ghcr.io/piyushkumar-1/light-vm:{{ .Version }}-arm64"
  - name_template: "ghcr.io/piyushkumar-1/light-vm:latest"
    image_templates:
      - "ghcr.io/piyushkumar-1/light-vm:{{ .Version }}-amd64"
      - "ghcr.io/piyushkumar-1/light-vm:{{ .Version }}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
