FROM alpine:3.20
RUN apk --no-cache add ca-certificates tzdata && \
    adduser -D -h /app lightvm
USER lightvm
WORKDIR /app
COPY light_vm /usr/local/bin/light_vm
VOLUME ["/app/data"]
EXPOSE 9090
ENTRYPOINT ["light_vm"]
CMD ["--config", "/app/light_vm.yml"]
